# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f285173451dd27b4558636bcecb3ba6a42172344e8df2345a922e6d0cfc51f16ad2669e4edaf55e68b72ee7e323f0a917a9823229d91b188dc567cb7823c1bd

test:
  secret_key_base: b586c0eda08e2fb3ea7cebec7d605f4663388e55a7e4b93dd5fe2f0681b05d9514c8d11e788705a72e5b85d6c193ec8723ce119c03af6f2c6e7c4a0967285189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
